language: sh

addons:
  apt:
    packages:
      - build-essential

env:
  global:
    - ZSH_DIST=$HOME/.zsh
  matrix:
    - ZSH_VERSION=5.3.1
    - ZSH_VERSION=5.3
    - ZSH_VERSION=5.2
    - ZSH_VERSION=5.1.1
    - ZSH_VERSION=5.1
    - ZSH_VERSION=5.0.8
    - ZSH_VERSION=5.0.2

cache:
  directories:
    - $ZSH_DIST

before_script:
  - >
    setup_zsh() {
      dest="$ZSH_DIST/$1"
      if [[ ! -d $dest/bin ]]; then
        tmp="$(mktemp --directory --tmpdir="${TMPDIR:/tmp}" zshbuild.XXXXXX)"
        (
          cd "$tmp" &&
          curl -L http://downloads.sourceforge.net/zsh/zsh-${1}.tar.gz | tar zx &&
          cd zsh-$1 &&
          ./configure --prefix="$dest" &&
          make &&
          mkdir -p "$dest" &&
          make install ||
          echo "Failed to build zsh-${1}!"
        )
      fi
      export PATH="$dest/bin:$PATH"
    }
  - setup_zsh $ZSH_VERSION
  - zsh --version

script:
  - zsh test.zsh -v
